### PR TITLE
Table v2

### PR DESCRIPTION
**Pull request by ldietz08**
- Created new table using react-data-table-component library
- Added loading animation component
- Made some stylistic changes 
- Switched to "" throughout all files

### CODE REVIEW

**Comment by amirobinsonmuto** [comment]
The table looks great!!! But the rows don't get updated with filters. You should include 'results' in the dependency array of your useEffect, then it might fix it. 

I noticed that now the footer is not pushed all the way down to the bottom. I suspect that's because the height is not specified and hence 'flex' is not pushing it all the way down. Adding back h-12 (or whatever number) should solve it. The footer and header look better, thank you for the styling updates!

**Comment by ldietz08** [comment]
Oh you're totally right, I only tested the sliders for some reason. I'll get on that this evening. 
Thanks @amirobinsonmuto !!

**Comment by ldietz08** [comment]
Thanks @bot-jamesschulz ! I removed the rows per page dropdown entirely. 

Also, I increased the padding on the filters so they don't get squished into the sliders at smaller screen sizes. I'll push all the changes up later this evening!

**Comment by ldietz08** [comment]
Yeah, I made the changes! Feel free to merge it to dev.

**Pull request merged**
